"""Resamples a complex Sentinel1 burst."""
import numpy as np

from eos.sar import regist, roi, io
from . import doppler_info


def burst_resample_from_meta(burst_meta, dst_burst_shape, matrix,
                             doppler, **kwargs):
    """Create a Sentinel1BurstResample instance from a Sentinel1Model\
    instance and additional parameters.

    Parameters
    ----------
    burst_meta : dict
        Metadata of the burst to be resampled.
    dst_burst_shape : tuple
        (h, w) shape of the destination burst.
    matrix : ndarray
        Affine registration matrix.
    doppler: eos.products.sentinel1.Sentinel1Doppler
        Object used to compute the Doppler info within a burst
    **kwargs: Keyword arguments of the constructor
        [dst_roi_in_burst, src_roi_in_burst]

    Returns
    -------
    Sentinel1BurstResample
        Instance that can be used to resample the complex burst array.
    """

    return Sentinel1BurstResample(burst_meta['burst_roi'], dst_burst_shape, matrix, doppler,
                                  burst_meta['lines_per_burst'],
                                  burst_meta['azimuth_frequency'],
                                  burst_meta['range_frequency'],
                                  burst_meta['slant_range_time'],
                                  burst_meta['burst_times'], **kwargs)


class Sentinel1BurstResample(regist.SarResample):
    """Resample a complex Sentinel1 burst.

    For more info:
    Miranda, N. (2015). Definition of the TOPS SLC deramping function
    for products generated by the S-1 IPF. 1–15.
    """

    def __init__(self, src_burst_roi, dst_burst_shape, burst_matrix,
                 doppler: doppler_info.Sentinel1Doppler,
                 lines_per_burst,
                 azimuth_frequency, range_frequency, slant_range_time,
                 burst_times, dst_roi_in_burst=None, src_roi_in_burst=None):
        """Instantiate a Sentinel1BurstResample object.

        Parameters
        ----------
        src_burst_roi : tuple
            (col, row, w, h) of the burst roi in the sentinel1 product
            of the burst to be resampled.
        dst_burst_shape : tuple
            (h, w) of the destination burst.
        burst_matrix : 3x3 ndarray
            Resampling matrix such as burst_matrix*dst_coord = src_coord of bursts
        doppler : Sentinel1Doppler
        lines_per_burst : int
            Lines per burst (with invalid data)
            as read from sentinel1 metadata.
        azimuth_frequency : float
            Azimuth sampling frequency.
        range_frequency : float
            Range sampling frequency.
        slant_range_time : float
            Two way range time of first (invalid) column in the burst.
        burst_times : tuple
            (start, start_valid, end_valid) azimuth times.
        dst_roi_in_burst : eos.sar.roi.Roi, optional.
            dst roi in dst burst coordinates. If None, the whole destination
            burst is considered. The default is None.
        src_roi_in_burst : eos.sar.roi.Roi, optional.
            src roi in src burst coordinates. If None, the whole source
            burst is considered. The default is None.

        Returns
        -------
        None.

        """
        # set the abstract variables
        # burst level quantities
        self.src_burst_roi = roi.Roi.from_roi_tuple(src_burst_roi)
        self.dst_burst_shape = dst_burst_shape
        self.burst_matrix = burst_matrix
        self.doppler = doppler

        # replicate some quantities
        # set resampling params
        if src_roi_in_burst is None:
            # whole source burst is considered
            h, w = self.src_burst_roi.get_shape()
            src_roi_in_burst = roi.Roi(0, 0, w, h)
        if dst_roi_in_burst is None:
            # whole destination frame will be considered
            h, w = dst_burst_shape
            dst_roi_in_burst = roi.Roi(0, 0, w, h)

        col_src, row_src = src_roi_in_burst.get_origin()
        col_dst, row_dst, w_dst, h_dst = dst_roi_in_burst.to_roi()

        # adapt the matrix
        self.matrix = regist.change_resamp_mat_orig(row_dst, col_dst,
                                                    row_src, col_src,
                                                    self.burst_matrix)
        # change self.src_roi_in_burst
        self.src_roi_in_burst = src_roi_in_burst

        # change self.dst_shape
        self.dst_shape = (h_dst, w_dst)

        # set the product variables
        self.lines_per_burst = lines_per_burst

        self.azimuth_frequency = azimuth_frequency
        self.range_frequency = range_frequency

        self.slant_range_time = slant_range_time

        # set variables specific to burst
        self.burst_times = burst_times

    def get_resampler_on_different_roi(
            self, dst_roi_in_burst: roi.Roi,
            src_roi_in_burst: roi.Roi):
        """
        Create a new instance (copy), but on different roi.

        Parameters
        ----------
        dst_roi_in_burst : roi.Roi
            dst roi in dst burst coordinates.
        src_roi_in_burst : roi.Roi
            src roi in src burst coordinates.

        Returns
        -------
        Sentinel1BurstResample
            A new instance of Sentinel1BurstResample set on the new rois.

        """
        # create a new instance with similar stuff, but on different roi
        return Sentinel1BurstResample(
            self.src_burst_roi.to_roi(), self.dst_burst_shape,
            self.burst_matrix, self.doppler,
            self.lines_per_burst, self.azimuth_frequency, self.range_frequency,
            self.slant_range_time, self.burst_times,
            dst_roi_in_burst, src_roi_in_burst)

    def src_roi_from_dst_roi(self, dst_roi_in_burst, margin=5):
        """
        Get the source roi in burst from the destination roi in burst.

        Parameters
        ----------
        dst_roi_in_burst : eos.sar.roi.Roi
            dst roi in dst burst coordinates.
        margin : int, optional
            Pixel safety margin to be applied after warping the destination roi.
            The default is 5.

        Returns
        -------
        src_roi_in_burst: eos.sar.roi.Roi.
            src roi in src burst coordinates

        """
        src_roi_in_burst = dst_roi_in_burst.warp_valid_roi(
            self.dst_burst_shape, self.src_burst_roi.get_shape(),
            self.burst_matrix, margin=margin)
        return src_roi_in_burst

    def to_eta_slrt(self, row, col):
        """Convert row, col to eta, slrt.

        Parameters
        ----------
        row : ndarray
            Row with respect to first valid line in the burst.
        col : ndarray
            Col with respect to the first valid column in the burst.

        Returns
        -------
        eta : ndarray
            Azimuth time w.r.t. the central line in the burst.
            The central line takes into account invalid lines.
        slrt : ndarray
            Range dependent doppler rate, i.e. the classical
            (stripmap) azimuth fm rate.
            We call it range dependent because it is computed as a polynomial
            w.r.t. range. A doppler rate denotes the rate at which
            the azimuth frequency is shifted along the aquisition.

        """
        eta = (self.burst_times[1] - self.burst_times[0]) \
            + (row - (self.lines_per_burst - 1) / 2) / self.azimuth_frequency
        slrt = (self.src_burst_roi.col + col) / self.range_frequency \
            + self.slant_range_time
        return eta, slrt

    def original_doppler(self):
        """
        Compute the doppler quantities on the original (as given in the esa tiff)\
        burst regular grid that has not undergone any resampling.

        Returns
        -------
        eta : 2d array of shape (Nlines_roi, 1)
            Azimuth time referenced to burst mid time.
        ref_time : 2d array of shape (1, Ncolumns_roi)
            Azimuth doppler reference time.
        dop_centroid : 2d array (1, Ncolumns_roi)
            Doppler centroid.
        dop_rate : 2d array (1, Ncolumns_roi)
            Doppler rate.

        """
        col0, row0, w, h = self.src_roi_in_burst.to_roi()

        eta, slrt = self.to_eta_slrt(np.arange(row0, row0 + h),
                                     np.arange(col0, col0 + w))

        # all Doppler quantities
        rg_dpt_dop_rate = self.doppler.get_rg_dpt_dop_rate(slrt)
        dop_centroid = self.doppler.get_dop_centroid(slrt)
        del slrt
        ref_time = self.doppler.get_ref_time(dop_centroid, rg_dpt_dop_rate)
        dop_rate = self.doppler.get_dop_rate(rg_dpt_dop_rate)
        del rg_dpt_dop_rate

        # reshape the 1D vectors for broadcasting
        dop_centroid = dop_centroid[None, :]
        ref_time = ref_time[None, :]
        dop_rate = dop_rate[None, :]
        eta = eta[:, None]
        return eta, ref_time, dop_centroid, dop_rate

    def deramp(self, src_array):
        """Deramp on the regular grid of the src array.

        Parameters
        ----------
        src_array : ndarray
            Burst array to be deramped.

        Returns
        -------
        ndarray
            Deramped burst.
            The fourrier spectrum now has no aliasing in azimuth and is
            centered around the zero frequency. Resampling can be safely
            done after this step.

        """
        assert src_array.shape == self.src_roi_in_burst.get_shape(), "src array is not of the expected shape"

        # get params necessary for deramping computation
        eta, ref_time, dop_centroid, dop_rate = self.original_doppler()

        # Compute Deramping func
        deta = eta - ref_time
        del eta, ref_time
        phi = (-np.pi * dop_rate * deta - 2 * np.pi * dop_centroid) * deta

        deramping_func = np.exp(1j * phi, dtype=np.complex64)

        return src_array * deramping_func

    def resampled_doppler(self, row_dst, col_dst):
        """
        Compute the doppler quantities on a set of points in the destination \
            coordinate system (i.e. after resampling).

        Parameters
        ----------
        row_dst : 1darray
            Rows in the new coord system within the dst roi.
        col_dst : 1d array
            Cols in the new coord system within the dst roi.

        Returns
        -------
        eta : 1darray
            Azimuth time referenced to burst mid time.
        ref_time : 1darray
            Azimuth doppler reference time.
        dop_centroid : 1darray
            Doppler centroid.
        dop_rate : 1darray
            Doppler rate.

        """
        # homogeneous coordinates
        dst_points = np.vstack(
            [row_dst, col_dst, np.ones(row_dst.size)])
        del col_dst, row_dst

        # irregular grid at src
        row_src, col_src = self.matrix.dot(dst_points)[:2]
        del dst_points

        # reference row_src and col_src w.r.t. the burst origin
        col_roi, row_roi = self.src_roi_in_burst.to_roi()[:2]
        row_src += row_roi
        col_src += col_roi

        eta, slrt = self.to_eta_slrt(row_src, col_src)
        del row_src, col_src

        # all Doppler quantities
        rg_dpt_dop_rate = self.doppler.get_rg_dpt_dop_rate(slrt)
        dop_centroid = self.doppler.get_dop_centroid(slrt)
        del slrt

        ref_time = self.doppler.get_ref_time(dop_centroid, rg_dpt_dop_rate)
        dop_rate = self.doppler.get_dop_rate(rg_dpt_dop_rate)
        del rg_dpt_dop_rate

        return eta, ref_time, dop_centroid, dop_rate

    def reramp(self, dst_array):
        """Reramp on the regular grid of the destination array\
        after resampling. Therefore, this corresponds to an irregular grid in\
        the source array. The deramping phase is estimated at each pixel of\
        the irregular grid and compensated.

        Parameters
        ----------
        dst_array : ndarray
            Resampled burst.

        Returns
        -------
        ndarray
            Reramped burst.

        """
        assert dst_array.shape == self.dst_shape, "destination array is not of the expected shape"
        # regular dst grid
        col_dst, row_dst = np.meshgrid(
            np.arange(self.dst_shape[1]), np.arange(self.dst_shape[0]))

        eta, ref_time, dop_centroid, dop_rate = self.resampled_doppler(
            row_dst.ravel(), col_dst.ravel())

        # Compute reramping func
        deta = eta - ref_time
        del eta, ref_time
        phi = np.pi * dop_rate * deta ** 2 +\
            2 * np.pi * dop_centroid * deta

        reramping_func = np.exp(1j * phi, dtype=np.complex64)

        return dst_array * reramping_func.reshape(self.dst_shape)


def get_read_roi_src_and_resampler(resampler, dst_roi_in_burst,
                                   burst_orig_src_in_tiff, margin=5):
    """
    Use the resampler already set on the burst (containing burst resampling matrix)
    to get the roi in the source burst. Use burst_orig to get where we need to read.\
    Update the resampler on the roi. src and dst refer to source and destination,\
        because the function is called in a context where a source region needs
        to be resampled onto a destination region.

    Parameters
    ----------
    resampler: Sentinel1BurstResample
        Resampler set on the burst under study.
    dst_roi_in_burst : eos.sar.roi.Roi
        roi of the destination region w.r.t. the burst coordinate system.
    burst_orig_src_in_tiff : tuple
        (col, row) the location of the burst orig in the tiff for the source grid.
    margin : int, optional
        Pixel safety margin to be applied after warping the destination region. The default is 5.

    Returns
    -------
    read_roi_src : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the source grid. It
        is obtained after warping dst_roi_in_burst and adding a safety margin, and shifting the origin.
    resampler_on_roi : Sentinel1BurstResample
        Resampler that can be directly applied on the array read using read_roi_src.

    """
    # warp the roi
    src_roi_in_burst = resampler.src_roi_from_dst_roi(dst_roi_in_burst, margin)

    col_src, row_src = burst_orig_src_in_tiff
    # read_roi in src burst, adding the origin
    read_roi_src = src_roi_in_burst.translate_roi(col_src, row_src)

    # get the new resampler
    resampler_on_roi = resampler.get_resampler_on_different_roi(dst_roi_in_burst,
                                                                src_roi_in_burst)
    return read_roi_src, resampler_on_roi


def warp_roi_read_resample(resampler, dst_roi_in_burst,
                           burst_orig_src_in_tiff, image_reader, get_complex=True,
                           margin=5, reramp=True):
    """
    Warp the roi to the source frame, read, then resample to the destination frame.

    Parameters
    ----------
    resampler: Sentinel1BurstResample
        Resampler set on the burst under study.
    dst_roi_in_burst : eos.sar.roi.Roi
        roi of the destination region w.r.t. the burst coordinate system.
    burst_orig_src_in_tiff : tuple
        (col, row) the location of the burst orig in the tiff for the source grid.
    image_reader : opened rasterio dataset or any object supporting windowed reading \
        `image_reader.read(1, window=((row, row+h), (col, col+w)))`
        Reader on the source tiff.
    get_complex : boolean, optional
        If True, the complex array is read and resampled. The default is True.
    margin : int, optional
        Pixel safety margin to be applied after warping the destination region. The default is 5.
    reramp : bool
        Set to False to avoid reramping after resampling.

    Returns
    -------
    burst_array_resamp : ndarray
        Resampled source array onto the destination region.
    read_roi_src : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the source grid. It
        is obtained after warping read_roi_dst and adding a safety margin.
    resampler_on_roi : Sentinel1BurstResample
        Resampler that was applied on the array read using read_roi_src.
    """
    read_roi_src, resampler_on_roi = get_read_roi_src_and_resampler(
        resampler, dst_roi_in_burst, burst_orig_src_in_tiff, margin)

    padded_burst_array = io.read_window(
        image_reader, read_roi_src, get_complex)

    burst_array_resamp = resampler_on_roi.resample(padded_burst_array, reramp=reramp)

    return burst_array_resamp, read_roi_src, resampler_on_roi
