"""Resamples a complex Sentinel1 burst."""
import numpy as np
from eos.sar import regist, orbit

def burst_resample_from_meta(burst_meta, dst_burst_shape, matrix, **kwargs):
    """Create a Sentinel1BurstResample instance from a Sentinel1Model\
    instance and additional parameters.

    Parameters
    ----------
    burst_meta : dict
        Metadata of the burst to be resampled.
    dst_burst_shape : tuple
        (h, w) shape of the destination burst.
    matrix : ndarray
        Affine registration matrix.
    **kwargs :
        Additional key word arguments to
        pass to the constructor of Sentinel1BurstResample.

    Returns
    -------
    Sentinel1BurstResample
        Instance that can be used to resample the complex burst array.
    """
    return Sentinel1BurstResample(burst_meta['burst_roi'], dst_burst_shape, matrix,
                                  burst_meta['lines_per_burst'],
                                  burst_meta['samples_per_burst'],
                                  burst_meta['azimuth_frequency'],
                                  burst_meta['range_frequency'],
                                  burst_meta['slant_range_time'],
                                  burst_meta['burst_times'],
                                  burst_meta['az_fm_times'],
                                  burst_meta['az_fm_info'],
                                  burst_meta['dc_estimate_time'],
                                  burst_meta['dc_estimate_t0'],
                                  burst_meta['dc_estimate_poly'],
                                  burst_meta['steering_rate'],
                                  burst_meta['wave_length'],
                                  burst_meta['state_vectors'],
                                  **kwargs)


class Sentinel1BurstResample(regist.ComplexResample):
    """Resample a complex Sentinel1 burst.

    For more info:
    Miranda, N. (2015). Definition of the TOPS SLC deramping function
    for products generated by the S-1 IPF. 1–15.
    """

    def __init__(self, src_burst_roi, dst_burst_shape, matrix,
                 lines_per_burst, samples_per_burst,
                 azimuth_frequency, range_frequency, slant_range_time,
                 burst_times,
                 az_fm_times, az_fm_info,
                 dc_estimate_time, dc_estimate_t0, dc_estimate_poly,
                 steering_rate, wave_length,
                 state_vectors, degree=11):
        """Instantiate a Sentinel1BurstResample object.

        Parameters
        ----------
        src_burst_roi : tuple
            (col, row, w, h) of the burst roi in the sentinel1 product
            of the burst to be resampled.
        dst_burst_shape : tuple
            (h, w) of the destination burst.
        matrix : 3x3 ndarray
            Resampling matrix such as matrix*dst_coord = src_coord of bursts
        lines_per_burst : int
            Lines per burst (with invalid data)
            as read from sentinel1 metadata.
        samples_per_burst : int
            Samples per burst (with invalid data)
            as read from sentinel1 metadata
        azimuth_frequency : float
            Azimuth sampling frequency.
        range_frequency : float
            Range sampling frequency.
        slant_range_time : float
            Two way range time of first (invalid) column in the burst.
        burst_times : tuple
            (start, start_valid, end_valid) azimuth times.
        az_fm_times : List
            Timestamps of azimuth times where we have polynomials
            of azimuth fm rate ( see definition below).
        az_fm_info : List of lists of float
            Azimuth fm rate polynomials
            Each list corresponds to an azimuth timestamp. The first element is
            a range time offset. The other three correspond to polynomial
            coefficients with respect to the slant range time to
            which offset has been applied.
        dc_estimate_time : List
            Timestamps of azimuth times where we have polynomials of
            the doppler centroid (see below).
        dc_estimate_t0 : List
            Offset of the slant range time.
        dc_estimate_poly : List of lists.
            List of polynomials of the doppler centroid.
            The elements correspond to polynomial coefficients
            with respect to the slant range time to which
            offset has been applied.
        steering_rate : float
            steering rate in rad/sec of the EM beam (TOPSAR mode).
        wave_length : float
            Carrier wavelength.
        state_vectors : Iterable of dict
            List of state vectors (time, position, velocity).
        degree : int, optional
            Degree of polynomial interpolating the orbit. The default is 11.

        Returns
        -------
        None.

        """
        # set the abstract variables
        # burst level quantities
        self.src_burst_roi = src_burst_roi
        self.dst_burst_shape = dst_burst_shape 
        self.burst_matrix = matrix
        
        # replicate these quantities
        # as resampling params
        # by default, the resampling in the burst is set as the whole burst      
        self.set_to_default_roi()
        
        # set the product variables
        self.lines_per_burst = lines_per_burst
        self.samples_per_burst = samples_per_burst

        self.azimuth_frequency = azimuth_frequency
        self.range_frequency = range_frequency

        self.slant_range_time = slant_range_time

        # set variables specific to burst
        self.burst_times = burst_times

        # get the burst deramping info
        # burst mid time
        burst_mid_time = self.burst_times[0] + \
            (self.lines_per_burst - 1) / (2 * self.azimuth_frequency)

        # find the times closest to mid time of metadata polys
        self.az_fm_info = az_fm_info[find_nearest_index(
            az_fm_times, burst_mid_time)]

        dc_id = find_nearest_index(dc_estimate_time, burst_mid_time)

        self.dc_t0 = dc_estimate_t0[dc_id]
        self.dc_poly = dc_estimate_poly[dc_id]

        # interpolate the speed
        orb = orbit.Orbit(state_vectors, degree=degree)
        speed = np.linalg.norm(orb.evaluate(burst_mid_time, order=1))

        # doppler rate due to rotation of EM beam
        self.krot = 2 * speed * steering_rate / wave_length

    def to_eta_slrt(self, row, col):
        """Convert row, col to eta, slrt.

        Parameters
        ----------
        row : ndarray
            Row with respect to first valid line in the burst.
        col : ndarray
            Col with respect to the first valid column in the burst.

        Returns
        -------
        eta : ndarray
            Azimuth time w.r.t. the central line in the burst.
            The central line takes into account invalid lines.
        slrt : ndarray
            Range dependent doppler rate, i.e. the classical
            (stripmap) azimuth fm rate.
            We call it range dependent because it is computed as a polynomial
            w.r.t. range. A doppler rate denotes the rate at which
            the azimuth frequency is shifted along the aquisition.

        """
        eta = (self.burst_times[1] - self.burst_times[0]) \
            + (row - (self.lines_per_burst - 1)/2) / self.azimuth_frequency
        slrt = (self.src_burst_roi[0] + col)/self.range_frequency \
            + self.slant_range_time
        return eta, slrt

    def get_rg_dpt_dop_rate(self, slrt):
        """Compute range dependent doppler rate from range time (slrt).

        Parameters
        ----------
        slrt : ndarray
             Two slant range time.

        Returns
        -------
        ndarray
            range dependent Doppler rate.
        """
        return np.polynomial.polynomial.polyval(
            slrt - self.az_fm_info[0],
            self.az_fm_info[1:4])

    def get_dop_centroid(self, slrt):
        """Compute the doppler centroid at range time (slrt).

        Parameters
        ----------
        slrt : ndarray
             Two slant range time.

        Returns
        -------
        ndarray
            Doppler centroid, i.e. the average azimuth frequency shift.

        """
        return np.polynomial.polynomial.polyval(
            slrt - self.dc_t0,
            self.dc_poly)

    def get_ref_time(self, dop_centroid, rg_dpt_dop_rate):
        """Compute the azimuth reference time from the doppler centroid\
        and the azimuth fm range dependent doppler rate.

        Parameters
        ----------
        dop_centroid : ndarray
            Doppler centroid on a set of points.
        rg_dpt_dop_rate : ndarray
            Azimuth fm rate on a set of points.

        Returns
        -------
        reference_time : ndarray
            Azimuth time (eta) used as offset in deramping formula.
            This is the eta at which the frequency shift is 0.
        """
        mid_swath_slrt = (self.samples_per_burst / 2) / self.range_frequency \
            + self.slant_range_time

        dop_centroid_mid = self.get_dop_centroid(mid_swath_slrt)
        rg_dpt_dop_rate_mid = self.get_rg_dpt_dop_rate(mid_swath_slrt)

        ref_time = dop_centroid_mid / rg_dpt_dop_rate_mid - \
            dop_centroid / rg_dpt_dop_rate

        return ref_time

    def get_dop_rate(self, rg_dpt_dop_rate):
        """Compute the total doppler rate by combining the azimuth fm range\
        dependent doppler rate with the EM beam rotation doppler rate.

        Parameters
        ----------
        rg_dpt_dop_rate : ndarray
            Azimuth fm (stripmap) doppler rate.

        Returns
        -------
        ndarray
            TOPSAR resulting doppler rate.
            The resulting doppler rate is obtained by accounting for
            the EM beam rotation.

        """
        return rg_dpt_dop_rate * self.krot / \
            (rg_dpt_dop_rate - self.krot)

    def set_inside_burst(self, dst_roi_in_burst, src_roi_in_burst): 
        """
        Set the resampling region source and destination within the bursts. 

        Parameters
        ----------
        dst_roi_in_burst : tuple
            (col, row, w, h) dst roi in dst burst coordinates.
        src_roi_in_burst : tuple
            (col, row, w, h) src roi in src burst coordinates..

        Returns
        -------
        None.

        """
        # change self.matrix 
        col_src, row_src = src_roi_in_burst[:2]
        col_dst, row_dst = dst_roi_in_burst[:2]
        
        self.matrix = regist.change_resamp_mat_orig(row_dst, col_dst, 
                                                   row_src, col_src,
                                                   self.burst_matrix)
        # change self.src_roi_in_burst
        self.src_roi_in_burst = src_roi_in_burst
        
        # change self.dst_shape
        self.dst_shape = (dst_roi_in_burst[3], dst_roi_in_burst[2])
    
    def set_to_default_roi(self): 
        """Reset the resampling to the whole burst."""
        self.src_roi_in_burst = (0, 0, self.src_burst_roi[2], self.src_burst_roi[3])
        self.dst_shape = self.dst_burst_shape
        self.matrix = self.burst_matrix
    
    def deramp(self, src_array) :
        """Deramp on the regular grid of the src array.

        Parameters
        ----------
        src_array : ndarray
            Burst array to be deramped.

        Returns
        -------
        ndarray
            Deramped burst.
            The fourrier spectrum now has no aliasing in azimuth and is
            centered around the zero frequency. Resampling can be safely
            done after this step.

        """
        col0, row0, w, h = self.src_roi_in_burst
        assert src_array.shape == (h, w), "src array is not of the expected shape"
        eta, slrt = self.to_eta_slrt(np.arange(row0, row0 + h),
                                     np.arange(col0, col0 + w))

        # all Doppler quantities
        rg_dpt_dop_rate = self.get_rg_dpt_dop_rate(slrt)
        dop_centroid = self.get_dop_centroid(slrt)
        del slrt
        ref_time = self.get_ref_time(dop_centroid, rg_dpt_dop_rate)
        dop_rate = self.get_dop_rate(rg_dpt_dop_rate)
        del rg_dpt_dop_rate

        # reshape the 1D vectors for broadcasting
        dop_centroid = dop_centroid[None, :]
        ref_time = ref_time[None, :]
        dop_rate = dop_rate[None, :]
        eta = eta[:, None]

        # Compute Deramping func
        deta = eta - ref_time
        del eta, ref_time
        phi = (-np.pi * dop_rate * deta - 2 * np.pi * dop_centroid) * deta

        deramping_func = np.exp(1j * phi, dtype=np.complex64)

        return src_array * deramping_func

    def reramp(self, dst_array):
        """Reramp on the regular grid of the destination array\
        after resampling. Therefore, this corresponds to an irregular grid in\
        the source array. The deramping phase is estimated at each pixel of\
        the irregular grid and compensated.

        Parameters
        ----------
        dst_array : ndarray
            Resampled burst.

        Returns
        -------
        ndarray
            Reramped burst.

        """
        assert dst_array.shape == self.dst_shape, "destination array is not of the expected shape"
        # regular dst grid
        col_dst, row_dst = np.meshgrid(
            np.arange(self.dst_shape[1]), np.arange(self.dst_shape[0]))

        # homogeneous coordinates
        dst_points = np.vstack(
            [row_dst.ravel(), col_dst.ravel(), np.ones(row_dst.size)])
        del col_dst, row_dst

        # irregular grid at src
        row_src, col_src = self.matrix.dot(dst_points)[:2]
        del dst_points

        # reference row_src and col_src w.r.t. the burst origin
        row_src += self.src_roi_in_burst[1]
        col_src += self.src_roi_in_burst[0]

        eta, slrt = self.to_eta_slrt(row_src, col_src)
        del row_src, col_src

        # all Doppler quantities
        rg_dpt_dop_rate = self.get_rg_dpt_dop_rate(slrt)
        dop_centroid = self.get_dop_centroid(slrt)
        del slrt
        ref_time = self.get_ref_time(dop_centroid, rg_dpt_dop_rate)
        dop_rate = self.get_dop_rate(rg_dpt_dop_rate)
        del rg_dpt_dop_rate

        # Compute reramping func
        deta = eta - ref_time
        del eta, ref_time
        phi = np.pi * dop_rate * deta ** 2 +\
            2 * np.pi * dop_centroid * deta

        reramping_func = np.exp(1j * phi, dtype=np.complex64)

        return dst_array * reramping_func.reshape(self.dst_shape)


def find_nearest_index(l, x):
    """Find the index of the item closest to a point in a list of floats.

    Parameters
    ----------
    l : list of floats
        List where we need to search for closest parameter.
    x : float
        Target point value.

    Returns
    -------
    best_index : int
        Index in the list where the best match
        (min absolute deviation) was found.

    """
    best_index = 0
    best_distance = np.inf
    for i, v in enumerate(l):
        d = np.abs(v - x)
        if d < best_distance:
            best_index = i
            best_distance = d
    return best_index
