"""Resamples a complex Sentinel1 burst."""
import numpy as np

from eos.sar import regist, roi, io
from . import doppler_info

def burst_resample_from_meta(burst_meta, dst_burst_shape, matrix,
        doppler=None, doppler_kwargs={}, **kwargs):
    """Create a Sentinel1BurstResample instance from a Sentinel1Model\
    instance and additional parameters.

    Parameters
    ----------
    burst_meta : dict
        Metadata of the burst to be resampled.
    dst_burst_shape : tuple
        (h, w) shape of the destination burst.
    matrix : ndarray
        Affine registration matrix.
    doppler: eos.products.sentinel1.Sentinel1Doppler
        Object used to compute the Doppler info within a burst
    doppler_kwargs: dict 
        Keywords used to instantiate the doppler object if not given
    **kwargs :
        Additional key word arguments to
        pass to the constructor of Sentinel1BurstResample.

    Returns
    -------
    Sentinel1BurstResample
        Instance that can be used to resample the complex burst array.
    """
    if not doppler:
        doppler = doppler_info.doppler_from_meta(burst_meta, **doppler_kwargs)
    return Sentinel1BurstResample(burst_meta['burst_roi'], dst_burst_shape, matrix, doppler,
                                  burst_meta['lines_per_burst'],
                                  burst_meta['azimuth_frequency'],
                                  burst_meta['range_frequency'],
                                  burst_meta['slant_range_time'],
                                  burst_meta['burst_times'],
                                  **kwargs)


class Sentinel1BurstResample(regist.SarResample):
    """Resample a complex Sentinel1 burst.

    For more info:
    Miranda, N. (2015). Definition of the TOPS SLC deramping function
    for products generated by the S-1 IPF. 1–15.
    """

    def __init__(self, src_burst_roi, dst_burst_shape, matrix,
                 doppler: doppler_info.Sentinel1Doppler,
                 lines_per_burst,
                 azimuth_frequency, range_frequency, slant_range_time,
                 burst_times):
        """Instantiate a Sentinel1BurstResample object.

        Parameters
        ----------
        src_burst_roi : tuple
            (col, row, w, h) of the burst roi in the sentinel1 product
            of the burst to be resampled.
        dst_burst_shape : tuple
            (h, w) of the destination burst.
        matrix : 3x3 ndarray
            Resampling matrix such as matrix*dst_coord = src_coord of bursts
        doppler : Sentinel1Doppler
        lines_per_burst : int
            Lines per burst (with invalid data)
            as read from sentinel1 metadata.
        azimuth_frequency : float
            Azimuth sampling frequency.
        range_frequency : float
            Range sampling frequency.
        slant_range_time : float
            Two way range time of first (invalid) column in the burst.
        burst_times : tuple
            (start, start_valid, end_valid) azimuth times.

        Returns
        -------
        None.

        """
        # set the abstract variables
        # burst level quantities
        self.src_burst_roi = roi.Roi.from_roi_tuple(src_burst_roi)
        self.dst_burst_shape = dst_burst_shape 
        self.burst_matrix = matrix
        self.doppler = doppler

        # replicate these quantities
        # as resampling params
        # by default, the resampling in the burst is set as the whole burst      
        self.set_to_default_roi()

        # set the product variables
        self.lines_per_burst = lines_per_burst

        self.azimuth_frequency = azimuth_frequency
        self.range_frequency = range_frequency

        self.slant_range_time = slant_range_time

        # set variables specific to burst
        self.burst_times = burst_times

    def to_eta_slrt(self, row, col):
        """Convert row, col to eta, slrt.

        Parameters
        ----------
        row : ndarray
            Row with respect to first valid line in the burst.
        col : ndarray
            Col with respect to the first valid column in the burst.

        Returns
        -------
        eta : ndarray
            Azimuth time w.r.t. the central line in the burst.
            The central line takes into account invalid lines.
        slrt : ndarray
            Range dependent doppler rate, i.e. the classical
            (stripmap) azimuth fm rate.
            We call it range dependent because it is computed as a polynomial
            w.r.t. range. A doppler rate denotes the rate at which
            the azimuth frequency is shifted along the aquisition.

        """
        eta = (self.burst_times[1] - self.burst_times[0]) \
            + (row - (self.lines_per_burst - 1)/2) / self.azimuth_frequency
        slrt = (self.src_burst_roi.col + col)/self.range_frequency \
            + self.slant_range_time
        return eta, slrt

    def set_inside_burst(self, dst_roi_in_burst, src_roi_in_burst): 
        """
        Set the resampling region source and destination within the bursts. 

        Parameters
        ----------
        dst_roi_in_burst : eos.sar.roi.Roi
            dst roi in dst burst coordinates.
        src_roi_in_burst : eos.sar.roi.Roi
            src roi in src burst coordinates.

        Returns
        -------
        None.

        """
        # change self.matrix 
        col_src, row_src, _, _ = src_roi_in_burst.to_roi()
        col_dst, row_dst, w_dst, h_dst = dst_roi_in_burst.to_roi()
        
        self.matrix = regist.change_resamp_mat_orig(row_dst, col_dst, 
                                                   row_src, col_src,
                                                   self.burst_matrix)
        # change self.src_roi_in_burst
        self.src_roi_in_burst = src_roi_in_burst
        
        # change self.dst_shape
        self.dst_shape = (h_dst, w_dst)
    
    def set_to_default_roi(self): 
        """Reset the resampling to the whole burst."""
        h, w = self.src_burst_roi.get_shape()
        self.src_roi_in_burst = roi.Roi(0, 0, w, h)
        self.dst_shape = self.dst_burst_shape
        self.matrix = self.burst_matrix
    
    def deramp(self, src_array) :
        """Deramp on the regular grid of the src array.

        Parameters
        ----------
        src_array : ndarray
            Burst array to be deramped.

        Returns
        -------
        ndarray
            Deramped burst.
            The fourrier spectrum now has no aliasing in azimuth and is
            centered around the zero frequency. Resampling can be safely
            done after this step.

        """
        col0, row0, w, h = self.src_roi_in_burst.to_roi()
        assert src_array.shape == (h, w), "src array is not of the expected shape"
        eta, slrt = self.to_eta_slrt(np.arange(row0, row0 + h),
                                     np.arange(col0, col0 + w))

        # all Doppler quantities
        rg_dpt_dop_rate = self.doppler.get_rg_dpt_dop_rate(slrt)
        dop_centroid = self.doppler.get_dop_centroid(slrt)
        del slrt
        ref_time = self.doppler.get_ref_time(dop_centroid, rg_dpt_dop_rate)
        dop_rate = self.doppler.get_dop_rate(rg_dpt_dop_rate)
        del rg_dpt_dop_rate

        # reshape the 1D vectors for broadcasting
        dop_centroid = dop_centroid[None, :]
        ref_time = ref_time[None, :]
        dop_rate = dop_rate[None, :]
        eta = eta[:, None]

        # Compute Deramping func
        deta = eta - ref_time
        del eta, ref_time
        phi = (-np.pi * dop_rate * deta - 2 * np.pi * dop_centroid) * deta

        deramping_func = np.exp(1j * phi, dtype=np.complex64)

        return src_array * deramping_func

    def reramp(self, dst_array):
        """Reramp on the regular grid of the destination array\
        after resampling. Therefore, this corresponds to an irregular grid in\
        the source array. The deramping phase is estimated at each pixel of\
        the irregular grid and compensated.

        Parameters
        ----------
        dst_array : ndarray
            Resampled burst.

        Returns
        -------
        ndarray
            Reramped burst.

        """
        assert dst_array.shape == self.dst_shape, "destination array is not of the expected shape"
        # regular dst grid
        col_dst, row_dst = np.meshgrid(
            np.arange(self.dst_shape[1]), np.arange(self.dst_shape[0]))

        # homogeneous coordinates
        dst_points = np.vstack(
            [row_dst.ravel(), col_dst.ravel(), np.ones(row_dst.size)])
        del col_dst, row_dst

        # irregular grid at src
        row_src, col_src = self.matrix.dot(dst_points)[:2]
        del dst_points

        # reference row_src and col_src w.r.t. the burst origin

        col_roi, row_roi, _, _ = self.src_roi_in_burst.to_roi()
        row_src += row_roi
        col_src += col_roi

        eta, slrt = self.to_eta_slrt(row_src, col_src)
        del row_src, col_src

        # all Doppler quantities
        rg_dpt_dop_rate = self.doppler.get_rg_dpt_dop_rate(slrt)
        dop_centroid = self.doppler.get_dop_centroid(slrt)
        del slrt
        ref_time = self.doppler.get_ref_time(dop_centroid, rg_dpt_dop_rate)
        dop_rate = self.doppler.get_dop_rate(rg_dpt_dop_rate)
        del rg_dpt_dop_rate

        # Compute reramping func
        deta = eta - ref_time
        del eta, ref_time
        phi = np.pi * dop_rate * deta ** 2 +\
            2 * np.pi * dop_centroid * deta

        reramping_func = np.exp(1j * phi, dtype=np.complex64)

        return dst_array * reramping_func.reshape(self.dst_shape)


def get_read_roi_src_and_resampler(
        burst_resampling_matrix, burst_roi_dst, read_roi_dst, burst_roi_src,
        burst_meta_src, margin=5):
    """
    Use the burst resampling matrix to get the roi in the source where we need to read\
    and the associated resampler. src and dst refer to source and destination,\
        because the function is called in a context where a source region needs
        to be resampled onto a destination region.

    Parameters
    ----------
    burst_resampling_matrix : np.ndarray 3x3
        3x3 affine (inverse, i.e. from destination to source) resampling matrix of the burst.
    burst_roi_dst : eos.sar.roi.Roi
        Roi containing the location of the burst in the tiff for the destination grid.
    read_roi_dst : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the destination grid.
    burst_roi_src : eos.sar.roi.Roi
        Roi containing the location of the burst in the tiff for the source grid.
    burst_meta_src : dict
        Metadata of the burst in the source product.
    margin : int, optional
        Pixel safety margin to be applied after warping the destination region. The default is 5.

    Returns
    -------
    read_roi_src : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the source grid. It
        is obtained after warping read_roi_dst and adding a safety margin.
    resampler : Sentinel1BurstResample
        Resampler that can be directly applied on the array read using read_roi_src.

    """
    # get the roi w.r.t. burst origin
    col_dst, row_dst, w_dst, h_dst = burst_roi_dst.to_roi()
    dst_roi_in_burst = read_roi_dst.translate_roi(-col_dst, -row_dst)

    # warp the roi
    col_src, row_src, w_src, h_src = burst_roi_src.to_roi()
    src_roi_in_burst = dst_roi_in_burst.warp_valid_roi(
        (h_dst, w_dst), (h_src, w_src), burst_resampling_matrix, margin=margin)

    # burst resampler
    resampler = burst_resample_from_meta(
        burst_meta_src, dst_burst_shape=(h_dst, w_dst),
        matrix=burst_resampling_matrix
    )

    # set to resample within the burst
    resampler.set_inside_burst(dst_roi_in_burst, src_roi_in_burst)

    # read_roi in src burst
    read_roi_src = src_roi_in_burst.translate_roi(col_src, row_src)

    return read_roi_src, resampler


def warp_roi_read_resample(
        burst_resampling_matrix, burst_roi_dst, read_roi_dst, burst_roi_src,
        burst_meta_src, image_reader, get_complex=True, margin=5):
    """
    Warp the roi to the source frame, read, then resample to the destination frame.

    Parameters
    ----------
    burst_resampling_matrix : np.ndarray 3x3
        3x3 affine (inverse, i.e. from destination to source) resampling matrix of the burst.
    burst_roi_dst : eos.sar.roi.Roi
        Roi containing the location of the burst in the tiff for the destination grid.
    read_roi_dst : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the destination grid.
    burst_roi_src : eos.sar.roi.Roi
        Roi containing the location of the burst in the tiff for the source grid.
    burst_meta_src : dict
        Metadata of the burst in the source product.
    image_reader : opened rasterio dataset or any object supporting windowed reading \
        `image_reader.read(1, window=((row, row+h), (col, col+w)))`
        Reader on the source tiff.
    get_complex : boolean, optional
        If True, the complex array is read and resampled. The default is True.
    margin : int, optional
        Pixel safety margin to be applied after warping the destination region. The default is 5.

    Returns
    -------
    burst_array_resamp : ndarray
        Resampled source array onto the destination region.
    read_roi_src : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the source grid. It
        is obtained after warping read_roi_dst and adding a safety margin.
    resampler : Sentinel1BurstResample
        Resampler that was applied on the array read using read_roi_src.
    """
    # this is in the only case you just need to read the rois
    if burst_resampling_matrix is None:
        return io.read_window(image_reader, read_roi_dst, get_complex),\
            read_roi_dst, None

    read_roi_src, resampler = get_read_roi_src_and_resampler(
        burst_resampling_matrix, burst_roi_dst, read_roi_dst, burst_roi_src,
        burst_meta_src, margin)

    padded_burst_array = io.read_window(
        image_reader, read_roi_src, get_complex)

    burst_array_resamp = resampler.resample(padded_burst_array)

    return burst_array_resamp, read_roi_src, resampler