default:
  image: python:3.9

stages:
  - test
  - deploy

variables:
  PIP_EXTRA_INDEX_URL: "https://pypi.dev-kayrros.ovh/"

test:
  stage: test
  before_script:
    - pip install cython numpy
    - pip install -e ".[test]"
    - pip install pytest-parallel
    - pip install py  # see https://github.com/browsertron/pytest-parallel/issues/118
  script:
    - pip install multidem 'kayrros-phoenix[source-s3]'
    - pytest . --workers auto

checkstyle:
  stage: test
  before_script:
    - pip install flake8==4.0.1
  script:
    - flake8 --show-source .

fakedeploy:
  stage: test
  before_script:
    - pip install twine
    - pip install cython numpy
  script:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - pip install dist/*.tar.gz
    - pip install dist/*.whl

deploy:
  stage: deploy
  before_script:
    - pip install twine
    - pip install cython numpy
  script:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - pip install dist/*.tar.gz
    - pip install dist/*.whl
    - twine upload
      --repository-url ${PIP_EXTRA_INDEX_URL}
      -u ${PYPI_USERNAME}
      -p ${PYPI_PASSWORD}
      dist/*
  only:
    - tags

