default:
  image: python:3.8

stages:
  - test
  - deploy

variables:
  PIP_EXTRA_INDEX_URL: "https://pypi.dev-kayrros.ovh/"
  GDAL_HTTP_UNSAFESSL: "YES"

test:
  stage: test
  before_script:
    - pip install -e ".[test]"
  script:
    - pytest .

deploy:
  stage: deploy
  before_script:
    - pip install twine
  script:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - pip install dist/*.tar.gz
    - pip install dist/*.whl
    - twine upload
      --repository-url ${PIP_EXTRA_INDEX_URL}
      -u ${PYPI_USERNAME}
      -p ${PYPI_PASSWORD}
      dist/*
  only:
    - tags
