default:
  image: python:3.9

stages:
  - test
  - deploy

variables:
  PIP_EXTRA_INDEX_URL: "https://pypi.dev-kayrros.ovh/"

test:
  stage: test
  tags:
    - high
  before_script:
    - pip install cython numpy
    - pip install -e ".[test]"
    - pip install pytest-xdist
  script:
    - pip install multidem 'kayrros-phoenix[source-s3]' dem-stitcher srtm4
    - pytest . -n auto

checkstyle:
  stage: test
  before_script:
    - pip install ruff==0.1.4
  script:
    - ruff check .
    - ruff format --check .

mypy:
  stage: test
  before_script:
    - pip install mypy~=1.6.0 cython numpy
    - pip install -e ".[test]"
  script:
    - mypy --non-interactive eos/ teosar/ tests/ usage/

fakedeploy:
  stage: test
  before_script:
    - pip install twine
    - pip install cython numpy
  script:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - pip install dist/*.tar.gz
    - pip install dist/*.whl

deploy:
  stage: deploy
  before_script:
    - pip install twine
    - pip install cython numpy
  script:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - pip install dist/*.tar.gz
    - pip install dist/*.whl
    - twine upload
      --repository-url ${PIP_EXTRA_INDEX_URL}
      -u ${PYPI_USERNAME}
      -p ${PYPI_PASSWORD}
      dist/*
  only:
    - tags
